version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
  graphql:
    image: node:18.3.0-alpine
    working_dir: /app
    ports:
      - 3000:3000
    entrypoint: /app/entrypoint.sh
    command: yarn dev:server
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
      DATA_PROXY_API_KEY: custometoken
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
  https-portal3000:
    image: steveltn/https-portal:1
    ports:
      - 443:443
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:3000'
volumes:
  node_modules: